[tool.coverage.run]
branch = true
include = [
    "cs_tools/**",
]

[tool.coverage.report]
precision = 2
show_missing = true
omit = [
    "**/_version.py",
    "**/__init__.py"
]
exclude_lines = [
    "if __name__ == .__main__.:",
]

[tool.ward]
path = ["tests"]
