[tool.poetry]
name = "thoughtspot_internal"
version = "0.1.0"
description = "Python interface for working with the ThoughtSpot API and platform"
authors = ["Customer Success @ ThoughtSpot <ps-na@thoughtspot.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
thoughtspot = {git = "https://github.com/thoughtspot/ts_tools.git"}

[tool.poetry.dev-dependencies]
ipykernel = "^5.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
