[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"


[project]
name = "cs_tools"
version = "1.4.0b0"
description = """\
	Tools created by the ThoughtSpot PS/CS organization to assist implementation and \
    administration of your platform.\
"""
readme = "README.md"
requires-python = ">=3.7"
license = {file = "LICENSE"}
authors = [
	{name = "boonhapus", email="nicholas.cooper@thoughtspot.com"},
	{name = "billdback-ts", email="bill.back@thoughtspot.com"},
	{name = "devinmcpherson-ts", email="devin.mcpherson@thoughtspot.com"},
	{name = "mishathoughtspot", email="misha.beek@thoughtspot.com"},
]
maintainers = [
    {name = "boonhapus", email="nicholas.cooper@thoughtspot.com"},
]
classifiers = [
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Intended Audience :: End Users/Desktop",
    "Operating System :: OS Independent",
    "License :: Other/Proprietary License",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
]

dependencies = [
    # dependencies here are listed for cs_tools the library  (ie. import cs_tools)

    "awesomeversion",
    "httpx",
    "pydantic",
    "pendulum",
    "thoughtspot_tml @ https://github.com/thoughtspot/thoughtspot_tml/archive/v2.0.0.zip",
    "toml",

    # TODO: switch with Starlite...
    "uvicorn",
    "fastapi",

    # version specific
    "strenum >= 0.4.9; python_version < '3.11.0'",
]


[project.urls]
homepage = "https://thoughtspot.github.io/cs_tools/"
repository = "https://github.com/thoughtspot/cs_tools"
documentation = "https://thoughtspot.github.io/cs_tools/"

[project.optional-dependencies]
cli = [
    # pin these dependencies explicitly so we can ensure they work across environments
    # 
    # DEV NOTE @boonhapus 2023/01/14
    #   these are only the direct dependencies, NOT the transitive dependencies.. so we
    #   need an extra process to grab the grandchild dependencies so our direct reliance
    #   doesn't break when a child updates.
    #
    #   see dist/build.py for this purpose

    # platform-specific
    "pyreadline3 == 3.4.1 ; sys_platform == 'win32'",

    "httpx",
    "rich",
    "typer[all]",
    "sqlmodel"
    # Jinja2 = "^3.1.2"
    # uvicorn = "^0.19.0"
    # fastapi = "0.85.1"
    # starlette = "0.20.4"
    # oyaml = "^1.0"
]
dev = [
    "cs_tools[cli]",
    "black",
    "coverage[toml]",
    "isort",
    "nox",
    "rich",
    "ward",
]


[project.scripts]
cs_tools = "cs_tools.cli.main:run"
cstools = "cs_tools.cli.main:run"


[tool.isort]
profile = "black"
line_length = 120
from_first = true
length_sort = true
reverse_sort = true

[tool.black]
line-length = 120
exclude = '''
(
      __pycache__   # ignore compiled bytecode
    | \.venv*       # ignore virtual environments
    | \.nox         # ignore virtual environments
)
'''

[tool.ward]
path = "tests/"

[tool.coverage.run]
branch = true
include = [
    "src/**.py",
]
omit = [
    "src/thoughtspot_tml/_scriptability.py",
    "src/thoughtspot_tml/_compat.py",
    "__init__.py",
]

[tool.coverage.report]
exclude_lines = [
    "# pragma: no cover",
    "# pragma: peephole optimzer",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
    "if typing.TYPE_CHECKING:",
]
