[tool.poetry]
name = "thoughtspot"
version = "0.1.0"
description = "Python interface for working with the ThoughtSpot API and platform"
authors = ["Your Name <you@example.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
requests = "^2.24.0"
pydantic = "^1.6.1"
toml = "^0.10.1"
pandas = "==0.25.3"

[tool.poetry.dev-dependencies]
ipykernel = "^5.2.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
