[tool.poetry]
name = "cs_tools"
version = "0.1.0"
description="Python programming interface to the ThoughtSpot API and platform"
authors = ["Professional Services at ThoughtSpot <ps-na@thoughtspot.com>"]

[tool.poetry.dependencies]
python = "^3.6.1"
typer = "^0.3.2"
pydantic = {extras = ["email"], version = "^1.8.1"}
httpx = "^0.18.1"
toml = "^0.10.2"
rich = "^10.1.0"
pyreadline = [
    { version = "^2.1", markers = "sys_platform == 'win32'" }
]

[tool.poetry.dev-dependencies]


[tool.poetry.scripts]
cs_tools = "cs_tools.cli:run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
