# Example Template is below.

[thoughtspot]
host = '<fill me in>'
port = '<fill me in>'
disable_ssl = false

# Don't change anything below unless you know what you're doing!

[logging]
version = 1
disable_existing_loggers = true

[logging.formatters.simple]
format = "{levelname:8} {asctime} {module}:{lineno} {message}"
style = "{"
datefmt = "%Y-%m-%d %H:%M:%S"

[logging.handlers.console]
level = "DEBUG"
class = "logging.StreamHandler"
formatter = "simple"
stream = "ext://sys.stdout"

[root]
level = ["debug"]
handlers = ["console"]
