name: ":scroll: Incorrect Documentation"
description: Found something wrong with documentation? Report it here.
labels: [documentation, bug]
body:
  - type: markdown
    attributes:
      value: >-
        ## *Thanks for your interest in cs_tools!* :tada:

        This project is maintained by the Professional Services and Customer Success
        organizations at ThoughtSpot, meant to augment built-in platform tools, help
        with administration of and enhance adoption within your ThoughtSpot environment.

        That said, it is our passion project! While we make every opportunity to keep up
        to date, resolve issues, well-document our tools, and provide a great
        experience; **if you have a true support issue or are missing critical
        functionality** of your ThoughtSpot platform, we absolutely encourage you to
        reach out to your designated account team!
 
  - type: checkboxes
    id: checks
    attributes:
      label: First Stop
      description: Please confirm and check all the following options.
      options:
        - label: I have read and agreed to the ThoughtSpot Dev Tools EULA.
          required: true
        - label: >-
            I understand that if I have a critical issue with ThoughtSpot, I should
            reach out to my account team instead of cs_tools.
          required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: >-
        What is wrong with the docs?

        Write a short description telling us what the docs are missing, a link to where
        you found a typo, or if you thought something was generally confusing.
    validations:
      required: true
