name: 🐛 Bug Report
description: Found something wrong with cs_tools? Report it here.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: >-
        Thanks for your interest in cs_tools! 🎉

  - type: checkboxes
    id: checks
    attributes:
      label: First Stop
      description: Please confirm and check all the following options.
      options:
        - label: I have read and agreed to the ThoughtSpot Dev Tools EULA.
          required: true
        - label: I searched the cs_tools documentation, with the integrated search.
          required: true

  - type: textarea
    id: platform-configuration
    attributes:
      label: Platform Configuration
      description: Please include the output of `cs_tools platform`.
      placeholder: >-
        (.cs_tools) C:\work\thoughtspot\cs_tools>cs_tools platform

                [PLATFORM DETAILS]
                system: Windows (detail: Windows-10-10.0.19041-SP0)
                python: 3.8.5
                datetime: 2021-09-04 14:16:10-0500
                cs_tools: 1.2.0
    validations:
      required: true
 
  - type: textarea
    id: example
    attributes:
      label: Example Command
      description: >-
        Please add a self-contained, [minimal, reproducible, example](https://stackoverflow.com/help/minimal-reproducible-example) with your use case.

        If we can copy it, run it, and see it right away, there's a much higher chance we'll be able to help you.
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        What is the problem, question, or error?

        Write a short description telling me what you are doing, what you expect to happen, and what is currently happening.
    validations:
      required: true
