name: Deploy docs to GH Pages

on:
  push:
    branches:
      - master
      - holiday-planning

jobs:
 build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
    env:
      DISPLAY: :0
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      # GitHub Actions is headless, so we need an x-server
      - name: Setup xvfb (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get install -y xvfb libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libxcb-xinput0 libxcb-xfixes0
          # start xvfb in the background
          sudo /usr/bin/Xvfb $DISPLAY -screen 0 1280x1024x24 &

      - name: Install Python dependencies
        run: pip install -e .[docs]

      - name: Create a CS Tools configuration
        run: cs_tools config create --config non-prod --host https://my1.thoughtspot.cloud --username cs_tools --password THIS_IS_FAKE --default --overwrite

      - name: Build and Deploy Documentation
        run: mkdocs build
      # - run: mkdocs gh-deploy --force
